require("rayandrew.configs.ui")
require("rayandrew.configs.git")
require("rayandrew.configs.treesitter")
require("rayandrew.configs.telescope")
require("rayandrew.configs.lsp")
require("rayandrew.configs.null-ls")
require("rayandrew.configs.others")
